site_name: maginna
theme: cider
site_url: http://maginna.github.io/
site_author: maginna
copyright: "Cinder is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: 'cinder'
  colorsheme: github
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
    - smarty
    - admonition
